### ISSUE TITLE
Error readfloat and writefloat function not present in EEPROM 

### ISSUE THREAD

**Issue by MISSEY** [GreenPonik/DFRobot_ESP_PH_WITH_ADC_BY_GREENPONIK#1]
Below is Error
and I want to use ESP8266, how I can proceed.

```

'class EEPROMClass' has no member named 'readFloat'

     this->_neutralVoltage = EEPROM.readFloat(this->_eepromStartAddress); //load the neutral (pH = 7.0)voltage of the pH board from the EEPROM
```

**Comment by MkLHX** [comment]
Hello @MISSEY ,
Has you can see here  https://github.com/GreenPonik/DFRobot_ESP_PH_WITH_ADC_BY_GREENPONIK#compatibility the compatibility with ESP8266 is wrong, cause we use specifics method from ESP32 EEPROM library.
In ESP8266 you just have EEPROM.Read() and EEPROM.Write() methods see https://github.com/esp8266/Arduino/blob/1aeea124b358c3dc63e1c6fb96376695cf24840b/libraries/EEPROM/EEPROM.h#L35

So you can make PR to make compatible ESP8266 to this library or you fork it and write your own logic about ESP8266.

**Comment by MISSEY** [comment]
So if I will use ESP32, this library will work fine, as it again doesn't contain readfloat and writefloat function. ?

**Comment by MkLHX** [comment]
This [library](https://github.com/GreenPonik/DFRobot_ESP_PH_WITH_ADC_BY_GREENPONIK) works on ESP32 to read PH with ADS1115 and @DFRobot ph sensor kit.
The error about EEPROMClass is provided by the EEPROM library used in ESP8266 this is not our library and we don't need to write any update on our [library](https://github.com/GreenPonik/DFRobot_ESP_PH_WITH_ADC_BY_GREENPONIK) to make it compatibel with ESP8266.

So if you absolutely want  use ESP8266 you have make some code

**Comment by MISSEY** [comment]
Thank you so much for your help
For EEPROM library that you use in [this](https://github.com/espressif/arduino-esp32/blob/master/libraries/EEPROM/src/EEPROM.cpp) for ESP32, [library](https://github.com/espressif/arduino-esp32/blob/master/libraries/EEPROM/src/EEPROM.cpp) should be use right ??

**Comment by MkLHX** [comment]
I don't sure i understand, but we use EEPROM.h directly in arduino project or platformio project it's contained in the Espressif arduino-esp32 framework.
So if you use it it's should works

**Comment by Bigbeaqr207** [comment]
Hi MkLHX,

I have a similar issue with regards to readFloat and writeFloat...

"*** [/data/picow/.pioenvs/picow/src/main.cpp.o] Error 1
/data/picow/.piolibdeps/picow/DFRobot_ESP_PH_BY_GREENPONIK/src/DFRobot_ESP_PH.cpp: In member function 'void DFRobot_ESP_PH::begin()':
/data/picow/.piolibdeps/picow/DFRobot_ESP_PH_BY_GREENPONIK/src/DFRobot_ESP_PH.cpp:43:36: error: 'class EEPROMClass' has no member named 'readFloat'
   43 |     this->_neutralVoltage = EEPROM.readFloat(PHVALUEADDR); //load the neutral (pH = 7.0)voltage of the pH board from the EEPROM..

I'm using a Raspberry Pi Pico W. Is this something that can be sorted out easily, or am I dreaming too big just yet?

PS: I haven't programmed in ages, so I'm the equivalent of a Noob again.

**Comment by MkLHX** [comment]
Hi @Bigbeaqr207 
As you can see on the readme this example works only on esp32 in c++ platformio project.
So i can't give any support on raspberry pi pico w...

**Comment by Bigbeaqr207** [comment]
Hi @MkLHX ,

Thanks for letting me know. I've gone over to ESP32 anyway. I've had to many connectivity issues when I run updates on the Pico W. Thanks for taking the time to write the initial code for the ESP32 too. Much appreciated.
